services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      ENV_FILE: .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lending
    ports:
      - "5432:5432"
    volumes:
      - db_lending:/var/lib/postgresql/data

volumes:
    db_lending:
