# Generated by Django 4.2.4 on 2024-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[
                            ("assets", "Assets"),
                            ("liabilities", "Liabilities"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expenses", "Expenses"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "account_title",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("account_number", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
