# Generated by Django 4.2.4 on 2024-06-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ledger_accounts", "0001_initial"),
        ("clients", "0001_initial"),
        ("transactions", "0002_transactionentry_ledger_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_number",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("loan_terms", models.IntegerField(null=True)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "interest_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                            ("released", "Released"),
                            ("fully_paid", "Fully Paid"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("cancelled_date", models.DateField(blank=True, null=True)),
                ("fully_paid_date", models.DateTimeField(null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loan_product", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("penalty", models.IntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledger_accounts.ledgeraccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash")], default="cash", max_length=20
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(editable=False, max_length=15, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, max_length=50, null=True)),
                ("payment_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loan"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "terms",
                    models.IntegerField(
                        choices=[
                            ("60", "60"),
                            ("48", "48"),
                            ("36", "36"),
                            ("24", "24"),
                            ("18", "18"),
                            ("12", "12"),
                            ("6", "6"),
                            ("3", "3"),
                        ]
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.BooleanField(default=True)),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledger_accounts.ledgeraccount",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_product_terms",
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanAmortization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.IntegerField(null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "running_balance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("fully_paid", models.BooleanField(default=False)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loans.loanproduct",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="terms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loans.loanterm",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
    ]
