# Generated by Django 4.2.4 on 2024-04-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loan_product", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("penalty", models.IntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "terms",
                    models.IntegerField(
                        choices=[
                            ("60", "60"),
                            ("48", "48"),
                            ("36", "36"),
                            ("24", "24"),
                            ("18", "18"),
                            ("12", "12"),
                            ("6", "6"),
                            ("3", "3"),
                        ]
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.BooleanField(default=True)),
                (
                    "loan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_product_terms",
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_number",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("loan_terms", models.IntegerField(null=True)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "interest_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                            ("released", "Released"),
                            ("fully_paid", "Fully Paid"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("cancelled_date", models.DateField(blank=True, null=True)),
                ("fully_paid_date", models.DateTimeField(null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanproduct",
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanterm",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
