# Generated by Django 4.2.4 on 2024-04-04 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_loan_transaction_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 4, 9, 55, 58, 253044), null=True
            ),
        ),
    ]
