# Generated by Django 4.2.4 on 2024-04-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0007_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
